# Generated by Django 4.0.3 on 2022-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='svg_image',
            field=models.FileField(default='config/static/images/Combat.svg', upload_to='config/static/images/'),
        ),
    ]
