# Generated by Django 4.0.3 on 2022-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_svg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='svg_image',
            field=models.ImageField(default='config/static/images/Combat.svg', upload_to='config/static/images/'),
        ),
    ]
