# Generated by Django 4.0.3 on 2022-05-30 01:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_svg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('CPP', 'C/C++'), ('CS', 'C#'), ('JAV', 'Java'), ('JS', 'JavaScript'), ('HTM', 'HTML'), ('CSS', 'CSS')], max_length=3)),
                ('amount_of_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(upload_to='config/static/images/')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
