# Generated by Django 4.0.3 on 2022-05-30 02:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('C/C++', 'C/C++'), ('C#', 'C#'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS')], max_length=10),
        ),
    ]
