# Generated by Django 4.0.3 on 2022-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.TextField(default='Беларусь'),
        ),
    ]
